### ISSUE TITLE
file uploading is blocked by rule 921110

### ISSUE THREAD

**Issue by OdaiGH** [coreruleset/coreruleset#2046] opened 2021-03-28 09:58 UTC
### Description
file uploading is blocked by CRS if file contains http smuggling 
for example if a document contains explanation for http smuggling attack and how to do it and then i try to upload it it will get blocked by CRS and I get HTTP Request Smuggling Attack
### Audit Logs / Triggered Rule Numbers

rule that is triggered is 921110

### Your Environment

* CRS version (3.3):
* Paranoia level setting:
* ModSecurity version (3):
* Web Server and version (nginx 1.14.2):
* Operating System and version:
* linux debian

### Confirmation

[ True ] I have removed any personal data (email addresses, IP addresses,
    passwords, domain names) from any logs posted.

**Comment by fzipi** [comment] 2021-03-28 13:27
@OdaiGH Well, this happened to me a lot with Moodle for example for my courses in the University. When you try to explain attacks, it will of course block if you actually type your attack there. This is per design, right? The rules can't measure your intended behavior.

What I did in the past was, for example, uploading some image instead. You take a screenshot of the actual text, and you upload it so at least it can be seen.

I will remove the false positive here, because it is a good match.

**Comment by OdaiGH** [comment] 2021-03-28 14:30
> @OdaiGH Well, this happened to me a lot with Moodle for example for my courses in the University. When you try to explain attacks, it will of course block if you actually type your attack there. This is per design, right? The rules can't measure your intended behavior.
> 
> What I did in the past was, for example, uploading some image instead. You take a screenshot of the actual text, and you upload it so at least it can be seen.
> 
> I will remove the false positive here, because it is a good match.

Thats one nice workaround tho haha 

Anyway, isnt there a way to tell modsecurity to stop looking for culn within webkit ( while uploading file) yet blocking  any request that have another an http smuggling ? Hope you get my explanation

**Comment by azurit** [comment] 2021-03-28 15:08
@OdaiGH You can create an exclusion rule, that's the thing you are looking for.

**Comment by fzipi** [comment] 2021-03-28 15:11
Well, not really. What modsecurity sees is plain regular HTTP traffic. There is no distinction there.

But I get what you say: can we only check in the headers part, and not in the body?

And now my question is: can you do HTTP smuggling while doing multipart upload?

**Comment by OdaiGH** [comment] 2021-04-05 10:50
> @OdaiGH You can create an exclusion rule, that's the thing you are looking for.

any help ?

**Comment by OdaiGH** [comment] 2021-04-05 10:54
> Well, not really. What modsecurity sees is plain regular HTTP traffic. There is no distinction there.
> 
> But I get what you say: can we only check in the headers part, and not in the body?
> 
> And now my question is: can you do HTTP smuggling while doing multipart upload?

the structure of my uploading request is as follow:

`REQUEST HEADER

------webkitecd090--------
--filename="test.txt"---
CONTENT 
------webkitecd090--------
`

if content of file contains `POST /index.php` for instance, it will get blocked even though it is the content of the file . i want modsecurity to ignore whats inside webkit only so if an http smuggling request comes after `webkit` last part then this should be blocked

**Comment by dune73** [comment] 2021-04-06 07:19
The concept of rule exclusions is explained in great detail in the following two tutorials:

* https://www.netnea.com/cms/apache-tutorial-7_including-modsecurity-core-rules/
* https://www.netnea.com/cms/apache-tutorial-8_handling-false-positives-modsecurity-core-rule-set/

**Comment by dune73** [comment] 2021-04-16 10:33
Closing this since it's actually a valid alert.

**Closed by dune73** 2021-04-16 10:33 UTC
