### ISSUE TITLE
update file `unix-shell.data`

### ISSUE THREAD

**Issue by fzipi** [coreruleset/coreruleset#2628] opened 2022-06-13 13:22 UTC
The contents of this file can be extended with the contents from the well known repository https://gtfobins.github.io/.

Getting the list of binaries can be done using: `curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/GTFOBins/GTFOBins.github.io/contents/_gtfobins | jq '.[].name' | grep '.md' | tr -d '"' | cut -f1 -d`

**Comment by fzipi** [comment] 2022-06-13 13:32
The only thing is that we might need to add the proper prefix here 🤔 

Some of the commands will be found in `bin` and others in `sbin`.

**Comment by dune73** [comment] 2022-06-13 13:34
Would _gtfobins_ be the only source of truth for this data file?

**Comment by fzipi** [comment] 2022-06-13 13:35
No. But is the first one I got :)

**Comment by dune73** [comment] 2022-06-13 13:44
So the issue is actually finding additional file lists.

I am pointing this out, because we could be satisfied with a quick fix / automation of this list, close the issue and forget we are building on a weak base. Better adding additional lists.

**Comment by fzipi** [comment] 2022-06-13 14:13
If there are any, sure. This is going to be a problem for any other lists. Some items on the list might come from old issues/PRs (in this or other lists), or from presentations at a conference (which tend to be rather static). And by nature, they should be evaluated again once we define the threshold for updating. There might be new lists by that time.

**Comment by fzipi** [comment] 2022-06-13 22:03
We need to integrate also the lists from #2616

**Closed as completed** 2022-06-28 13:58 UTC
Labels: :zap: list update
