### ISSUE TITLE
Move DoS rules to plugin

### ISSUE THREAD

**Issue by fzipi** [coreruleset/coreruleset#2373] opened 2022-02-05 12:49 UTC
### Motivation

Per [meeting decision](https://github.com/coreruleset/coreruleset/issues/2330#issuecomment-1004310622), we are going to transfer these rules to a new DoS plugin.

### Proposed solution

- [x] Create new plugin structure and move files
- [x] Document change in CRS docs
- <del>[ ] Add documentation on expirevar problems and how to workaround</del>

### Additional context

- @theseion has [more information](https://github.com/SpiderLabs/ModSecurity/issues/1803#issuecomment-474884652)
- there is a discussion pending in our [meeting agenda](https://github.com/coreruleset/coreruleset/issues/2350) for expirevar in modsec3
- Partial work may already been done in https://github.com/coreruleset/dos-protection-plugin-modsecurity/issues/11

### Plugin repository

Find it here: https://github.com/coreruleset/dos-protection-plugin/ (AH: I added the link here for easy access.)

**Comment by RedXanadu** [comment] 2022-02-05 19:43
I was meaning to create an issue for this also :)

Do I understand correctly that the scope has changed? I thought the job was simply to move the existing rules to a plugin.

Are the rules being altered/rewritten with this new expirevar thing in mind?

**Comment by theseion** [comment] 2022-02-06 06:24
The problem is that `expirevar` doesn't work in the NGiNX implementation of ModSecurity. I constructed a workaround for the DOS rule a couple of years back and someone asked if that could be used by default for NGiNX. We will have to discuss that on Monday (I've put it on the agenda), but if we do it, I think it would make sense to move the rules first and then, possibly, make the change afterwards. I don't think we should do both at the same time.

**Comment by dune73** [comment] 2022-02-06 07:24
I agree on the idea to move and update afterwards. And it is already broken for NGINX. So moving won't change a thing and if we get a workaround afterwards, then cool.

**Comment by RedXanadu** [comment] 2022-02-09 19:37
Makes sense. Will go ahead with moving the rules out.

Added v4 milestone as these rules need to be moved out ahead of a 4.0 release.

**Comment by RedXanadu** [comment] 2022-03-20 16:00
First draft of DoS plugin is up, needs review:
[https://github.com/coreruleset/dos-protection-plugin](https://github.com/coreruleset/dos-protection-plugin)

**Comment by theseion** [comment] 2022-03-21 19:29
I did a pass and opened one issue. Otherwise it looks good to me.

**Comment by RedXanadu** [comment] 2022-03-27 16:39
Thanks for checking!

I've also now added the description of how the plugin works from the plugin file into the README, to provide documentation.

**Comment by theseion** [comment] 2022-03-29 10:27
@RedXanadu I'd also add something to the readme on where those variables are being set (-config.conf), so users aren't lost after reading "please make sure to set these variables".

**Comment by RedXanadu** [comment] 2022-03-30 20:46
@theseion Good shout. Done.

Also added a brief and simple "Testing" section, as I forgot that the official CRS plugin rules require a testing section :)

**Comment by RedXanadu** [comment] 2022-03-30 21:51
I think the remaining task is to carry out Nginx improvements/fixes?

**Comment by theseion** [comment] 2022-03-31 06:11
Great! Thanks @RedXanadu!

**Comment by RedXanadu** [comment] 2022-04-02 11:34
I've been thinking: anyone who has used the DoS mechanism in ModSecurity knows that it isn't great, and even can be quite unreliable when put under pressure / a real attack.

I propose adding a note to the DoS plugin repo README file. Something like: "Is this really the best solution for you? If you want something to handle **real** (D)DoS attacks then maybe look elsewhere", and maybe offer pointers for where to start looking for a more robust solution.

**Comment by dune73** [comment] 2022-04-02 12:51
Let me propose the following wording:

```
ModSecurity and CRS are suited to small scale application level DoS attacks. DoS attacks on the network level, distributed DoS attacks and larger DoS attacks are hard to fight on this platform. The reason is that the means of ModSecurity tend to degrade under load themselves.

In such a situation, we propose one or several of the following options:
* mod_reqtimeout on Apache for request delaying attacks like slowloris
* mod_evasive on Apache since it's been around for more than 20 years
* mod_qos on Apache giving you granular control over clients hammering your server
* Using a LoadBalancer / traffic washer with DoS capabilities
* A DoS protection service or Content Delivery Network
```

Additional options welcome.

**Comment by theseion** [comment] 2022-04-02 12:57
Great idea. Especially now, that we can provide it as a plugin.

**Comment by RedXanadu** [comment] 2022-04-03 16:33
That's excellent text, thank you @dune73!

Added to the README.

**Comment by dune73** [comment] 2022-04-03 18:10
Thank you very much.

**Comment by theseion** [comment] 2022-04-04 07:21
I've added an initial version of the v3 plugin here: https://github.com/coreruleset/dos-protection-plugin-modsecurity-v3. I've implemented the workaround but it needs to be tested.

**Comment by fzipi** [comment] 2022-11-15 12:10
@theseion @RedXanadu @dune73 What is needed here now? Can someone assign himself to this issue and make it pass over the finish line?

**Comment by theseion** [comment] 2022-11-15 19:42
Somebody needs to test the plugin. I have too many things on my plate at the moment to do that.

**Comment by dune73** [comment] 2022-11-20 22:42
I'm not really running ModSec3, so I am not sure I have the experience to understand and make this work.

@theMiddleBlue, you are working on ModSec3. Would you be able to test this plugin. It's kind of needed for v4.

**Comment by theMiddleBlue** [comment] 2022-11-21 08:31
I'm going to test it, I would like to create a backend on sandbox for plugins too

**Comment by dune73** [comment] 2022-11-21 08:41
Awesome. Thank you very much.

For the record: The fake bot plugin is a very nice test case for plugins. I reckon that would also make for a nice sandbox plugin test case.

**Comment by airween** [comment] 2022-11-21 09:55
Plugin contains (contained) a duplicated id, [#3](https://github.com/coreruleset/dos-protection-plugin-modsecurity-v3/pull/3) solves it.

**Comment by airween** [comment] 2022-11-21 14:45
I tried our DOS plugin for v3, but seems it does not work together with CRS.

DOS plugin config:
```
SecRule &TX:dos-protection-plugin_enabled "@eq 0" \
  "id:9515010,\
   phase:1,\
   pass,\
   nolog,\
   setvar:'tx.dos-protection-plugin_enabled=1'"
```
other variables are left as default.

First case:
```
Include /path/to/src/coreruleset/crs-setup.conf

Include /path/to/src/coreruleset-plugins/dos-protection-plugin-modsecurity-v3/plugins/dos-protection-config.conf
Include /path/to/src/coreruleset-plugins/dos-protection-plugin-modsecurity-v3/plugins/dos-protection-before.conf

Include /path/to/crs/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf
Include /path/to/crs/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf
```
As you can see, I just turned on the plugin without CRS rules (only the exclusion rules there are).

In this case I get this result with `ab`:
```
$ ab -n 10000 -c 300 -H "Host: localhost" http://172.35.40.16:8080/empty.html
This is ApacheBench, Version 2.3 <$Revision: 1843412 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 172.35.40.16 (be patient)
Completed 1000 requests
Completed 2000 requests
Completed 3000 requests
Completed 4000 requests
Completed 5000 requests
Completed 6000 requests
Completed 7000 requests
Completed 8000 requests
Completed 9000 requests
Completed 10000 requests
Finished 10000 requests


Server Software:        nginx/1.18.0
Server Hostname:        172.35.40.16
Server Port:            8080

Document Path:          /empty.html
Document Length:        27 bytes

Concurrency Level:      300
Time taken for tests:   6.659 seconds
Complete requests:      10000
Failed requests:        9200
   (Connect: 0, Receive: 0, Length: 9200, Exceptions: 0)
Non-2xx responses:      9200
Total transferred:      2994000 bytes
HTML transferred:       1429200 bytes
Requests per second:    1501.80 [#/sec] (mean)
Time per request:       199.761 [ms] (mean)
Time per request:       0.666 [ms] (mean, across all concurrent requests)
Transfer rate:          439.10 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        6   11   3.3     10      37
Processing:    40  185  25.4    182     459
Waiting:       26  185  25.4    182     459
Total:         51  196  25.6    192     496

Percentage of the requests served within a certain time (ms)
  50%    192
  66%    197
  75%    200
  80%    202
  90%    212
  95%    223
  98%    260
  99%    265
 100%    496 (longest request)
```

The point is:
```
Concurrency Level:      300
Time taken for tests:   6.659 seconds
Complete requests:      10000
Failed requests:        9200
   (Connect: 0, Receive: 0, Length: 9200, Exceptions: 0)
```

seems that DoS protection works. In the log, I got several lines like this (I added an `msg` action to rule 9515130):
```
2022/11/21 15:27:13 [error] 108141#108141: *9998 [client 172.35.40.100] ModSecurity: Access denied with code 403 (phase 1). Matched "Operator `Eq' with parameter `1' against variable `IP:::::DOS_BLOCK' (Value: `1' ) [file "/path/to/src/coreruleset-plugins/dos-protection-plugin-modsecurity-v3/plugins/dos-protection-before.conf"] [line "177"] [id "9515130"] [rev ""] [msg "Transaction has dropped"] [data ""] [severity "0"] [ver "OWASP_CRS/3.4.0-dev"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "paranoia-level/1"] [tag "attack-dos"] [tag "OWASP_CRS"] [tag "capec/1000/210/227/469"] [hostname "172.35.40.16"] [uri "/empty.html"] [unique_id "166904083318.281248"] [ref ""], client: 172.35.40.100, server: _, request: "GET /empty.html HTTP/1.0", host: "localhost"
```

Next test: I enabled CRS rules:
```
Include /path/to/src/coreruleset/crs-setup.conf

Include /path/to/src/coreruleset-plugins/dos-protection-plugin-modsecurity-v3/plugins/dos-protection-config.conf
Include /path/to/src/coreruleset-plugins/dos-protection-plugin-modsecurity-v3/plugins/dos-protection-before.conf

Include /path/to/src/coreruleset/rules/*.conf

Include /path/to/crs/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf
Include /path/to/crs/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf
```

Note, that `rules/*.conf` includes the `rules/REQUEST-901-INITIALIZATION.conf` too - may be there we clean something...?

But then `ab` gives:
```
Server Software:        nginx/1.18.0
Server Hostname:        172.35.40.16
Server Port:            8080

Document Path:          /empty.html
Document Length:        27 bytes

Concurrency Level:      300
Time taken for tests:   86.711 seconds
Complete requests:      10000
Failed requests:        0
Total transferred:      2580000 bytes
HTML transferred:       270000 bytes
Requests per second:    115.33 [#/sec] (mean)
Time per request:       2601.317 [ms] (mean)
Time per request:       8.671 [ms] (mean, across all concurrent requests)
Transfer rate:          29.06 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        6   16  80.1      9    1043
Processing:    70 2545 303.4   2522    4508
Waiting:       49 2545 303.4   2522    4507
Total:         77 2561 305.6   2532    4523

Percentage of the requests served within a certain time (ms)
  50%   2532
  66%   2604
  75%   2672
  80%   2699
  90%   2791
  95%   2939
  98%   3044
  99%   3081
 100%   4523 (longest request)
```
The total run time is very long, but number of failed requests is 0, and there is no any line in log with message `Access denied`.

Did i mess something up?

**Comment by theseion** [comment] 2022-11-21 20:54
Hm. weird. I'll have to look at it. Thanks for checking!

**Comment by fzipi** [comment] 2022-12-22 10:05
Removed from v4.

**Comment by theseion** [comment] 2023-09-17 19:38
I finally looked at this and from what I can tell, you might have forgotten to enable `900130` to initialise the IP collection. I tested with the v2 plugin but the same should apply to v3.

**Comment by theseion** [comment] 2023-09-17 20:21
Hm... Something else is weird with v3. One of the rules doesn't seem to be triggered at all... I'll investigate.

**Comment by theseion** [comment] 2023-09-18 13:01
Ok, so here's the rub: once again we have an issue with configuration order. The `initcol` actions are executed int `901-INITIALIZATION`, which is loaded _after_ the `*-before.conf` and `*-config.conf` files of the plugin. Hence, all plugin rules in phase 1 will be able to use the IP collection.

We've solved the default variables by copying them to the plugins, but I'm not sure we can do the same thing for `initcol`. I'm putting this on the agenda for tonight.

**Comment by fzipi** [comment] 2024-05-29 10:51
@theseion Do we need something else here?

**Comment by theseion** [comment] 2024-05-29 17:36
Yes. We had decided the following:

> 🔵 Decision: @theseion with help of @dune73 and @airween will try to check for initcol. If the collection is initialized by the plugin -> remove the 901 rule via ctl statement and do initcol yourself.

I don't think we ever got around to it.

On the other hand, we don't need the v3 plugin anymore because `expirevar` now works on v3, which makes the `initcol` issue less pressing.

So:
1. remove v3 plugin
2. finalize and test (v2) plugin
3. rename v2 plugin to just "DoS plugin"

**Comment by theseion** [comment] 2024-07-23 05:22
V3 plugin has been archived, v2 plugin is now the only DoS plugin.

**Comment by fzipi** [comment] 2024-10-20 01:26
Can we close this one then?

**Comment by theseion** [comment] 2024-10-21 05:03
The plugin still doesn't work properly. But yes, let's close this one.

**Closed by theseion** 2024-10-21 05:03 UTC
Labels: :+1: Feature Request, :jigsaw: plugin
