### ISSUE TITLE
Escape double quotation mark character in non-regex operator

### ISSUE THREAD

**Issue by capy3ra** [coreruleset/coreruleset#3816] opened 2024-09-09 11:12 UTC
I want to create a rule that filters double quotation mark characters using a non-regex operator.
Pattern: ``not "redirect" to``
I write the rule below:
```
SecRule ARGS|REQUEST_BODY "@streq not \"redirect\" to" "id:1,deny,log,..."
```
But it not working as I hope

**Comment by RedXanadu** [comment] 2024-09-09 11:52
Hello @capy3ra,

What you're asking is a general ModSecurity / SecLang question. We're happy to help! But if you have any similar, general _(not CRS-specific)_ questions or issues going forwards then the best places to ask are:

* the [ModSecurity GitHub page](https://github.com/owasp-modsecurity/ModSecurity/);
* the [ModSecurity Slack channel](https://owasp.slack.com/archives/C069PCXSW12);
* or the [ModSecurity mailing lists](https://sourceforge.net/p/mod-security/mailman/mod-security-users/).
* (And if you're unsure then there's also the [CRS Slack channel](https://owasp.slack.com/archives/CBKGH8A5P), where you can ask whatever questions you have and someone can definitely point you in the right direction or signpost you to the best place to ask :slightly_smiling_face:)

---

Anyway, let's answer your question.

Your rule looks fine to me *(and it works for me, too.)*

Which phase is your rule executing in? E.g. if your rule is executing in phase **1** (the request headers phase, no request body is yet available) but you're putting a test payload into the body of a request then the rule would not match.

Example rule (I used single quotes around my rule operator to make things tidier and easier to read):

```
SecRule ARGS|REQUEST_BODY '@streq not "redirect" to' \
    "id:1,\
    phase:2,\
    deny,\
    log"
```

Test command:

``
$ curl 127.0.0.1 --data 'test=not "redirect" to'
``

which, for me, results in a match:

```
[Mon Sep 09 11:44:11.128834 2024]
    [security2:error]
    [pid 30:tid 126360888542912]
    [client 172.18.0.1:43280]
    [client 172.18.0.1]
    ModSecurity: Warning. String match "not \\"redirect\\" to" at ARGS:test.
    [file "/etc/modsecurity.d/owasp-crs/rules/00_custom.conf"]
    [line "5"]
    [id "1"]
    [tag "modsecurity"]
    [hostname "example.com"]
    [uri "/"]
    [unique_id "Zt7fi3VWL0iargcZ1aWk4AAAAAA"]
```

Let me know if you have any further questions. If not, I'll close this issue later today. Thank you!

**Comment by capy3ra** [comment] 2024-09-09 16:18
I tried your rule but it doesn't work for me. 
Output: 
```
Expecting an action, got:  redirect" to' "id:1,phase:2,deny,log" in ...
```

**Comment by RedXanadu** [comment] 2024-09-09 17:06
@capy3ra What engine are you using?

**Comment by capy3ra** [comment] 2024-09-09 17:10
i using Modsecurity v3.0.12

**Comment by RedXanadu** [comment] 2024-09-09 18:02
I see. It certainly works as intended on Apache with ModSecurity v2.

I suspect that nginx and/or ModSecurity v3 have an issue with accepting escaped double quote marks with the `streq` operator. If there _is_ a simple or elegant way to do this then it isn't apparent.

You might want to ask how to escape a double quote mark `"` in the `streq` operator on the ModSecurity GitHub or the ModSecurity Slack channel.

In the meantime, here is a working solution: nginx + ModSecurity v3 work with the following regular expression:

```
SecRule ARGS|REQUEST_BODY "@rx ^not \"redirect\" to$" \
    "id:1,\
    phase:2,\
    deny,\
    log"
```

**Closed by RedXanadu** 2024-09-09 18:02 UTC
Labels: :no_entry: wontfix, :hourglass_flowing_sand: awaiting feedback
