### ISSUE TITLE
942200 blocking some Iphone user-agents | Matched Data: , like Gecko)...

### ISSUE THREAD

**Issue by isniukArte** [coreruleset/coreruleset#3732] opened 2024-06-06 11:13 UTC
### Description
We have a lot of absolutely legal requests from real users with User-Agent like this:
`Mozilla/5.0 (iPhone; CPU iPhone OS 16_5_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) GSA/318.0.636615128 Mobile/20F75 Safari/604.1 OcIdWebView ({"os":"iOS","appVersion":"318.0.636615128","app":"com.google.GoogleMobile","osVersion":"16.5.1","style":2,"isDarkTheme":false,"libraryVersion":"1.23.10.0","isBoldFont":true,"zoom":0.90913120567375882,"isHighContrast":false})`

These requests are blocked by 942200 with a reason:
`Matched Data: , like Gecko) GSA/318.0.636615128 Mobile/20F75 Safari/604.1 OcIdWebView ({"os":"iOS","appVersion":"318.0.636615128", found within REQUEST_HEADERS:user-agent: Mozilla/5.0 (iPhone; CPU iPhone OS 16_5_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) GSA/318.0.636615128 Mobile/20F75 Safari/604.1 OcIdWebView ({"os":"iOS","appVersion":"318.0.636615128","app":"com.google.GoogleMobile","osVersion":"16.5.1","style":2,"isDarkTheme":false,"libraryVersion":"1.23.10.0","isBoldFont":true,"zoom":0.90913120567375882,"isHighContrast":false})`

### How to reproduce the misbehavior (-> curl call)
```
curl -X GET host.with.pl2.enabled -kL \
-H 'user-agent: Mozilla/5.0 (iPhone; CPU iPhone OS 16_5_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) GSA/318.0.636615128 Mobile/20F75 Safari/604.1 OcIdWebView ({"os":"iOS","appVersion":"318.0.636615128","app":"com.google.GoogleMobile","osVersion":"16.5.1","style":2,"isDarkTheme":false,"libraryVersion":"1.23.10.0","isBoldFont":true,"zoom":0.90913120567375882,"isHighContrast":false})' \
-H "Host: host.with.pl2.enabled"
```
Here I used single quotes for passing a header. Double quotes in the user-agent will be stripped if you use double quotes for a header. In that case, the rule will not be triggered. So I think it is related to double quotes in User-Agent string.

### Your Environment

* CRS version (e.g., v3.3.4):4.3.0
* Paranoia level setting (e.g. PL1) :PL2
* ModSecurity version (e.g., 2.9.6): ModSecurity v3.0.12 (Linux)
* Web Server and version or cloud provider / CDN (e.g., Apache httpd 2.4.54): ingress-nginx controller v1.10.0
* Operating System and version: n/a

### Confirmation

[ ] I have removed any personal data (email addresses, IP addresses,
    passwords, domain names) from any logs posted.

**Comment by airween** [comment] 2024-06-06 11:39
Hi @isniukArte,

thanks for detailed reporting.

I can confirm, any request with this `User-Agent` header triggers rule [942200](https://github.com/coreruleset/coreruleset/blob/main/rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf#L823-L850).

Based on this [RFC](https://www.rfc-editor.org/rfc/rfc7231#page-46), I don't think this is a false positive (mainly this rule is on [PL2](https://github.com/coreruleset/coreruleset/blob/main/rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf#L843)). We can examine the problem in more depth, but I'm afraid the only solution would be that we split this rule (detach the target `REQUEST-HEADERS:User-Agent`).

I think the only solution is that you create an exclusion against rule (or only for the mentioned target).

**Comment by theseion** [comment] 2024-06-07 17:37
The user agent is perfectly valid, but it is still rather uncommon to send JSON as part of the user agent. The reason that the rule triggers is the comma, followed by something that could be hexadecimal encoded, and then a double quote.

I searched for `OcIdWebView` to figure out, which application could be responsible for the user agent but couldn't find anything. Again, I don't think that JSON is a thing (yet) in user agent strings (I could be wrong). I'm with @airween on this, you will need to create an exclusion rule to handle this because this is a special case.

**Comment by azurit** [comment] 2024-06-21 19:13
We definitely should not allow JSON in User-Agent. I suggest to close this.

@isniukArte Do you need help with writing an exclusion rule?

**Comment by azurit** [comment] 2024-07-15 07:54
@isniukArte ping.

**Comment by isniukArte** [comment] 2024-07-15 18:51
No, thanks, I made an exclusion on my own. Ads SDK sounds pretty strange. We don't have any integration in the product. But still beneficial information. Thank you.

**Comment by theseion** [comment] 2024-08-12 19:16
Closing as per discussion. @androidacy-user, if you have any further information you would like to share, feel free to reopen the issue.

**Closed by theseion** 2024-08-12 19:16 UTC
Labels: :heavy_plus_sign: False Positive
